### ISSUE TITLE
Can you please add support for Python3.6?

### ISSUE THREAD

**Issue by mashhoodgee** [chrivand/Firepower_O365_Feed_Parser#12]
I am getting a lot of dependencies errors and stuck with.
S@mate:~/scripts/Firepower_O365_Feed_Parser-asa_support# python3.6 O365_web_service_parser.py
Traceback (most recent call last):
  File "O365_web_service_parser.py", line 24, in <module>
    import webexteamssdk
ModuleNotFoundError: No module named 'webexteamssdk'

tried using pip install webexteamssdk
$: command not found

**then got installed**
pip3 install webexteamssdk
Collecting webexteamssdk

again run the script
S@mate:~/scripts/Firepower_O365_Feed_Parser-asa_support# python3.6 O365_web_service_parser.py
Traceback (most recent call last):
  File "O365_web_service_parser.py", line 29, in <module>
    from Asa import Asa
  File "/root/scripts/Firepower_O365_Feed_Parser-asa_support/Asa.py", line 16, in <module>
    from netmiko import ConnectHandler
ModuleNotFoundError: No module named 'netmiko'

**installed using**
pip3 install -U netmiko

again run the script and got the following error

S@mate:~/scripts/Firepower_O365_Feed_Parser-asa_support# python3.6 O365_web_service_parser.py
Traceback (most recent call last):
  File "O365_web_service_parser.py", line 29, in <module>
    from Asa import Asa
  File "/root/scripts/Firepower_O365_Feed_Parser-asa_support/Asa.py", line 16, in <module>
    from netmiko import ConnectHandler
**ModuleNotFoundError: No module named 'netmiko'**

**I run these commands and let worked like it should be.**
pip install --upgrade pip
pip3 install --upgrade pip
pip3 install netmiko

then got it started work.

S@mate:~/scripts/Firepower_O365_Feed_Parser-asa_support# python3.6 O365_web_service_parser.py

Loading config data...
Config loading complete.

TESTTEST
Do you want to update an FMC [f] or ASA [a] [f/a]:

Thanks for the script, it helped me a lot.

**Comment by chrivand** [comment]
this has been done, closing issue
