### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by richtown** [chrivand/Firepower_O365_Feed_Parser#14]
Hi there,

Thank you for writing the program; it is extremely useful to us.

We have started using a proxy and have noticed the program continues to send requests without going through a proxy first.

We see this whilst running tcpdump during program execution.

config.json settings:
    "PROXY": "true",
    "PROXY_USER": "",
    "PROXY_PASSWD": "",
    "PROXY_HOST": "*.*.*.*",
    "PROXY_PORT": "8080"

The program hangs on "Saving config data..."
python3 O365_web_service_parser.py

Loading config data...
Config loading complete.

Chosen O365 plan: Worldwide, chosen applications: All
Saving config data...

If you have the time to look at it, it would be appreciated.

Many thanks

**Comment by chrivand** [comment]
hi I have just fixed this bug. the problem was that I set a value to the JSON bool (true/false) even though the object was a Python dict, which uses capital letters (True/False). Thanks for reporting this!
