### ISSUE TITLE
Empty Config String Check Issues in O365WebServerParser.py

### ISSUE THREAD

**Issue by PAamac** [chrivand/Firepower_O365_Feed_Parser#5]
There are multiple empty config option string checks in O365WebServerParser.py that do not implement the check properly, e.g.:

if CONFIG_DATA['WEBEX_ACCESS_TOKEN'] is '' or CONFIG_DATA['WEBEX_ROOM_ID'] is '':

  With respect to this example, if neither of these two options are defined in config, the if statement will erroneously proceed to the "else" clause. In this case, in the "else" clause the script will attempt to use WebEx when no WebEx config options have been defined, causing the script to throw errors.

  Example fix:

if CONFIG_DATA['WEBEX_ACCESS_TOKEN'] == '' or CONFIG_DATA['WEBEX_ROOM_ID'] == '':

**Comment by chrivand** [comment]
thanks! fixed in v4.1
